version: '3'


services:
  app:
    container_name: AppointmentManager
    build: .
    ports:
      - "80:80"
    volumes:
      - "./pb_data:/app/pb_data"
      # use this to persist migrations 
      # - "./pb_migrations/:/app/pb_migrations"
